config/routes.rb
Rails.application.routes.draw do
  resources :albums
  resources :song_classes

end

app/models/album.rb
class Album < ActiveRecord::Base
end

app/models/song_class.rb
class SongClass < ActiveRecord::Base

	mount_uploader :audio_file, SonguploaderUploader

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:album_name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/song_classes_controller.rb
require 'pry'

class SongClassesController < ApplicationController
  before_action :set_song_class, only: [:show, :edit, :update, :destroy]

  # GET /song_classes
  # GET /song_classes.json
  def index
    @song_classes = SongClass.all
  end

  # GET /song_classes/1
  # GET /song_classes/1.json
  def show
  end

  # GET /song_classes/new
  def new
    @song_class = SongClass.new
  end

  # GET /song_classes/1/edit
  def edit
  end

  # POST /song_classes
  # POST /song_classes.json
  def create
    binding.pry
    @song_class = SongClass.new(song_class_params)
    @song_class.audio_file = params[:file]
    @song_class.song_name = params['song_class']['song_name']
    @song_class.album_ID = params['song_class']['album_ID']
    respond_to do |format|
      if @song_class.save
        format.html { redirect_to @song_class, notice: 'Song class was successfully created.' }
        format.json { render :show, status: :created, location: @song_class }
      else
        format.html { render :new }
        format.json { render json: @song_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /song_classes/1
  # PATCH/PUT /song_classes/1.json
  def update
    respond_to do |format|
      if @song_class.update(song_class_params)
        format.html { redirect_to @song_class, notice: 'Song class was successfully updated.' }
        format.json { render :show, status: :ok, location: @song_class }
      else
        format.html { render :edit }
        format.json { render json: @song_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /song_classes/1
  # DELETE /song_classes/1.json
  def destroy
    @song_class.destroy
    respond_to do |format|
      format.html { redirect_to song_classes_url, notice: 'Song class was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song_class
      @song_class = SongClass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def song_class_params
      params.require(:song_class).permit(:audio_file)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/song_classes_helper.rb
module SongClassesHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :album_name %><br>
    <%= f.text_field :album_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<table>
  <thead>
    <tr>
      <th>Album name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @albums.each do |album| %>
      <tr>
        <td><%= album.album_name %></td>
        <td><%= link_to 'Show', album %></td>
        <td><%= link_to 'Edit', edit_album_path(album) %></td>
        <td><%= link_to 'Destroy', album, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album name:</strong>
  <%= @album.album_name %>
</p>

<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeCarrier</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/song_classes/_form.html.erb
<%= form_for(@song_class) do |f| %>
  <% if @song_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song_class.errors.count, "error") %> prohibited this song_class from being saved:</h2>

      <ul>
      <% @song_class.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.collection_select :album_ID, Album.all, :id, :album_name, :prompt => 'Select an Album' %>
    <%= f.label :audio_file %><br>
    <%= f.text_field :song_name %><br>
    <%= f.file_field :audio_file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/song_classes/edit.html.erb
<h1>Editing Song Class</h1>

<%= render 'form' %>

<%= link_to 'Show', @song_class %> |
<%= link_to 'Back', song_classes_path %>

app/views/song_classes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Song Classes</h1>

<table>
  <thead>
    <tr>
      <th>Audio file</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @song_classes.each do |song_class| %>
      <tr>
        <td><%= song_class.song_name %></td>
        <td><%= link_to 'Show', song_class %></td>
        <td><%= link_to 'Edit', edit_song_class_path(song_class) %></td>
        <td><%= link_to 'Destroy', song_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Song class', new_song_class_path %>

app/views/song_classes/new.html.erb
<h1>New Song Class</h1>

<%= render 'form' %>

<%= link_to 'Back', song_classes_path %>

app/views/song_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Audio file:</strong>
  <%= @song_class.audio_file %>
</p>

<%= link_to 'Edit', edit_song_class_path(@song_class) %> |
<%= link_to 'Back', song_classes_path %>